AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  po-parse-samified

  Sample SAM Template for po-parse-samified

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  IngressS3Bucket:
    Type: AWS::S3::Bucket

  POParseFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: po_parse/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        POParseAPISource:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /poparse
            Method: get
        IngressS3BucketEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: IngressS3Bucket
            Events:
            - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: ingress
                  - Name: suffix
                    Value: .pdf
              
              

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  POParseAPI:
    Description: "API Gateway endpoint URL for Prod stage for PO Parse Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/poparse/"
  POParseFunction:
    Description: "PO Parse Function ARN"
    Value: !GetAtt POParseFunction.Arn
  POParseFunctionIamRole:
    Description: "Implicit IAM Role created for PO Parse function"
    Value: !GetAtt POParseFunctionRole.Arn
  IngressS3Bucket:
    Description: "ARN of S3 Bucket"
    Value: !GetAtt IngressS3Bucket.Arn
