AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  po-parse-sam2

  Sample SAM Template for po-parse-sam2

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  IngressS3Bucket2:
    Type: AWS::S3::Bucket


  POParse2Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: po_parse/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - AmazonS3ReadOnlyAccess
      Events:
        ## This is how we enter the function.
        ## We need to have an input which contains
        ParsePostReq:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /po_parse2
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  POParse2API:
    Description: "API Gateway endpoint URL PO Parse 2 Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  POParse2Function:
    Description: "PO Parse 2 Lambda Function ARN"
    Value: !GetAtt POParse2Function.Arn
  POParse2FunctionIamRole:
    Description: "Implicit IAM Role created for PO Parse 2 function"
    Value: !GetAtt POParse2FunctionRole.Arn
  IngressS3Bucket2:
    Description: "ARN of S3 Bucket"
    Value: !GetAtt IngressS3Bucket2.Arn
    Export:
      Name: IngressS3Bucket2Arn
  


